//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 10:04:16 AM CST 
//


package org.web3d.x3d.util.x3duom;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}FieldDeclaration" minOccurs="0"/&gt;
 *         &lt;element ref="{}GroupContentModel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{}NodeContentModel"/&gt;
 *           &lt;element ref="{}StatementContentModel"/&gt;
 *           &lt;element ref="{}SourceText" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldDeclaration",
    "groupContentModel",
    "nodeContentModelOrStatementContentModelOrSourceText"
})
@XmlRootElement(name = "ContentModel")
public class ContentModel {

    @XmlElement(name = "FieldDeclaration")
    protected FieldDeclaration fieldDeclaration;
    @XmlElement(name = "GroupContentModel")
    protected List<GroupContentModel> groupContentModel;
    @XmlElements({
        @XmlElement(name = "NodeContentModel", type = NodeContentModel.class),
        @XmlElement(name = "StatementContentModel", type = StatementContentModel.class),
        @XmlElement(name = "SourceText")
    })
    protected List<Object> nodeContentModelOrStatementContentModelOrSourceText;

    /**
     * Gets the value of the fieldDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link FieldDeclaration }
     *     
     */
    public FieldDeclaration getFieldDeclaration() {
        return fieldDeclaration;
    }

    /**
     * Sets the value of the fieldDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldDeclaration }
     *     
     */
    public void setFieldDeclaration(FieldDeclaration value) {
        this.fieldDeclaration = value;
    }

    /**
     * Gets the value of the groupContentModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupContentModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupContentModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupContentModel }
     * 
     * 
     */
    public List<GroupContentModel> getGroupContentModel() {
        if (groupContentModel == null) {
            groupContentModel = new ArrayList<GroupContentModel>();
        }
        return this.groupContentModel;
    }

    /**
     * Gets the value of the nodeContentModelOrStatementContentModelOrSourceText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeContentModelOrStatementContentModelOrSourceText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeContentModelOrStatementContentModelOrSourceText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeContentModel }
     * {@link StatementContentModel }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getNodeContentModelOrStatementContentModelOrSourceText() {
        if (nodeContentModelOrStatementContentModelOrSourceText == null) {
            nodeContentModelOrStatementContentModelOrSourceText = new ArrayList<Object>();
        }
        return this.nodeContentModelOrStatementContentModelOrSourceText;
    }

}
