//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 10:04:16 AM CST 
//


package org.web3d.x3d.util.x3duom;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieldTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fieldTypeValues"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="SFBool"/&gt;
 *     &lt;enumeration value="SFColor"/&gt;
 *     &lt;enumeration value="SFColorRGBA"/&gt;
 *     &lt;enumeration value="SFDouble"/&gt;
 *     &lt;enumeration value="SFFloat"/&gt;
 *     &lt;enumeration value="SFImage"/&gt;
 *     &lt;enumeration value="SFInt32"/&gt;
 *     &lt;enumeration value="SFMatrix3d"/&gt;
 *     &lt;enumeration value="SFMatrix3f"/&gt;
 *     &lt;enumeration value="SFMatrix4d"/&gt;
 *     &lt;enumeration value="SFMatrix4f"/&gt;
 *     &lt;enumeration value="SFNode"/&gt;
 *     &lt;enumeration value="SFRotation"/&gt;
 *     &lt;enumeration value="SFString"/&gt;
 *     &lt;enumeration value="SFTime"/&gt;
 *     &lt;enumeration value="SFVec2d"/&gt;
 *     &lt;enumeration value="SFVec2f"/&gt;
 *     &lt;enumeration value="SFVec3d"/&gt;
 *     &lt;enumeration value="SFVec3f"/&gt;
 *     &lt;enumeration value="SFVec4d"/&gt;
 *     &lt;enumeration value="SFVec4f"/&gt;
 *     &lt;enumeration value="MFBool"/&gt;
 *     &lt;enumeration value="MFColor"/&gt;
 *     &lt;enumeration value="MFColorRGBA"/&gt;
 *     &lt;enumeration value="MFDouble"/&gt;
 *     &lt;enumeration value="MFFloat"/&gt;
 *     &lt;enumeration value="MFImage"/&gt;
 *     &lt;enumeration value="MFInt32"/&gt;
 *     &lt;enumeration value="MFMatrix3d"/&gt;
 *     &lt;enumeration value="MFMatrix3f"/&gt;
 *     &lt;enumeration value="MFMatrix4d"/&gt;
 *     &lt;enumeration value="MFMatrix4f"/&gt;
 *     &lt;enumeration value="MFNode"/&gt;
 *     &lt;enumeration value="MFRotation"/&gt;
 *     &lt;enumeration value="MFString"/&gt;
 *     &lt;enumeration value="MFTime"/&gt;
 *     &lt;enumeration value="MFVec2d"/&gt;
 *     &lt;enumeration value="MFVec2f"/&gt;
 *     &lt;enumeration value="MFVec3d"/&gt;
 *     &lt;enumeration value="MFVec3f"/&gt;
 *     &lt;enumeration value="MFVec4d"/&gt;
 *     &lt;enumeration value="MFVec4f"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "fieldTypeValues")
@XmlEnum
public enum FieldTypeValues {

    @XmlEnumValue("SFBool")
    SF_BOOL("SFBool"),
    @XmlEnumValue("SFColor")
    SF_COLOR("SFColor"),
    @XmlEnumValue("SFColorRGBA")
    SF_COLOR_RGBA("SFColorRGBA"),
    @XmlEnumValue("SFDouble")
    SF_DOUBLE("SFDouble"),
    @XmlEnumValue("SFFloat")
    SF_FLOAT("SFFloat"),
    @XmlEnumValue("SFImage")
    SF_IMAGE("SFImage"),
    @XmlEnumValue("SFInt32")
    SF_INT_32("SFInt32"),
    @XmlEnumValue("SFMatrix3d")
    SF_MATRIX_3_D("SFMatrix3d"),
    @XmlEnumValue("SFMatrix3f")
    SF_MATRIX_3_F("SFMatrix3f"),
    @XmlEnumValue("SFMatrix4d")
    SF_MATRIX_4_D("SFMatrix4d"),
    @XmlEnumValue("SFMatrix4f")
    SF_MATRIX_4_F("SFMatrix4f"),
    @XmlEnumValue("SFNode")
    SF_NODE("SFNode"),
    @XmlEnumValue("SFRotation")
    SF_ROTATION("SFRotation"),
    @XmlEnumValue("SFString")
    SF_STRING("SFString"),
    @XmlEnumValue("SFTime")
    SF_TIME("SFTime"),
    @XmlEnumValue("SFVec2d")
    SF_VEC_2_D("SFVec2d"),
    @XmlEnumValue("SFVec2f")
    SF_VEC_2_F("SFVec2f"),
    @XmlEnumValue("SFVec3d")
    SF_VEC_3_D("SFVec3d"),
    @XmlEnumValue("SFVec3f")
    SF_VEC_3_F("SFVec3f"),
    @XmlEnumValue("SFVec4d")
    SF_VEC_4_D("SFVec4d"),
    @XmlEnumValue("SFVec4f")
    SF_VEC_4_F("SFVec4f"),
    @XmlEnumValue("MFBool")
    MF_BOOL("MFBool"),
    @XmlEnumValue("MFColor")
    MF_COLOR("MFColor"),
    @XmlEnumValue("MFColorRGBA")
    MF_COLOR_RGBA("MFColorRGBA"),
    @XmlEnumValue("MFDouble")
    MF_DOUBLE("MFDouble"),
    @XmlEnumValue("MFFloat")
    MF_FLOAT("MFFloat"),
    @XmlEnumValue("MFImage")
    MF_IMAGE("MFImage"),
    @XmlEnumValue("MFInt32")
    MF_INT_32("MFInt32"),
    @XmlEnumValue("MFMatrix3d")
    MF_MATRIX_3_D("MFMatrix3d"),
    @XmlEnumValue("MFMatrix3f")
    MF_MATRIX_3_F("MFMatrix3f"),
    @XmlEnumValue("MFMatrix4d")
    MF_MATRIX_4_D("MFMatrix4d"),
    @XmlEnumValue("MFMatrix4f")
    MF_MATRIX_4_F("MFMatrix4f"),
    @XmlEnumValue("MFNode")
    MF_NODE("MFNode"),
    @XmlEnumValue("MFRotation")
    MF_ROTATION("MFRotation"),
    @XmlEnumValue("MFString")
    MF_STRING("MFString"),
    @XmlEnumValue("MFTime")
    MF_TIME("MFTime"),
    @XmlEnumValue("MFVec2d")
    MF_VEC_2_D("MFVec2d"),
    @XmlEnumValue("MFVec2f")
    MF_VEC_2_F("MFVec2f"),
    @XmlEnumValue("MFVec3d")
    MF_VEC_3_D("MFVec3d"),
    @XmlEnumValue("MFVec3f")
    MF_VEC_3_F("MFVec3f"),
    @XmlEnumValue("MFVec4d")
    MF_VEC_4_D("MFVec4d"),
    @XmlEnumValue("MFVec4f")
    MF_VEC_4_F("MFVec4f");
    private final String value;

    FieldTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldTypeValues fromValue(String v) {
        for (FieldTypeValues c: FieldTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
