//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 10:04:16 AM CST 
//


package org.web3d.x3d.util.x3duom;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}componentInfo" minOccurs="0"/&gt;
 *         &lt;element ref="{}Inheritance" minOccurs="0"/&gt;
 *         &lt;element ref="{}AdditionalInheritance" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}field" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{}containerField" minOccurs="0"/&gt;
 *         &lt;element ref="{}ContentModel" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="specificationSection" type="{http://www.w3.org/2001/XMLSchema}string" default="" /&gt;
 *       &lt;attribute name="specificationUrl" type="{http://www.w3.org/2001/XMLSchema}string" default="" /&gt;
 *       &lt;attribute name="appinfo" type="{http://www.w3.org/2001/XMLSchema}string" default="" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentInfo",
    "inheritance",
    "additionalInheritance",
    "field",
    "containerField",
    "contentModel"
})
@XmlRootElement(name = "InterfaceDefinition")
public class InterfaceDefinition {

    protected ComponentInfo componentInfo;
    @XmlElement(name = "Inheritance")
    protected Inheritance inheritance;
    @XmlElement(name = "AdditionalInheritance")
    protected List<AdditionalInheritance> additionalInheritance;
    protected List<Field> field;
    protected ContainerField containerField;
    @XmlElement(name = "ContentModel")
    protected ContentModel contentModel;
    @XmlAttribute(name = "specificationSection")
    protected String specificationSection;
    @XmlAttribute(name = "specificationUrl")
    protected String specificationUrl;
    @XmlAttribute(name = "appinfo")
    protected String appinfo;

    /**
     * Gets the value of the componentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentInfo }
     *     
     */
    public ComponentInfo getComponentInfo() {
        return componentInfo;
    }

    /**
     * Sets the value of the componentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentInfo }
     *     
     */
    public void setComponentInfo(ComponentInfo value) {
        this.componentInfo = value;
    }

    /**
     * Gets the value of the inheritance property.
     * 
     * @return
     *     possible object is
     *     {@link Inheritance }
     *     
     */
    public Inheritance getInheritance() {
        return inheritance;
    }

    /**
     * Sets the value of the inheritance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inheritance }
     *     
     */
    public void setInheritance(Inheritance value) {
        this.inheritance = value;
    }

    /**
     * Gets the value of the additionalInheritance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalInheritance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalInheritance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalInheritance }
     * 
     * 
     */
    public List<AdditionalInheritance> getAdditionalInheritance() {
        if (additionalInheritance == null) {
            additionalInheritance = new ArrayList<AdditionalInheritance>();
        }
        return this.additionalInheritance;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    /**
     * Gets the value of the containerField property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerField }
     *     
     */
    public ContainerField getContainerField() {
        return containerField;
    }

    /**
     * Sets the value of the containerField property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerField }
     *     
     */
    public void setContainerField(ContainerField value) {
        this.containerField = value;
    }

    /**
     * Gets the value of the contentModel property.
     * 
     * @return
     *     possible object is
     *     {@link ContentModel }
     *     
     */
    public ContentModel getContentModel() {
        return contentModel;
    }

    /**
     * Sets the value of the contentModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentModel }
     *     
     */
    public void setContentModel(ContentModel value) {
        this.contentModel = value;
    }

    /**
     * Gets the value of the specificationSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationSection() {
        if (specificationSection == null) {
            return "";
        } else {
            return specificationSection;
        }
    }

    /**
     * Sets the value of the specificationSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationSection(String value) {
        this.specificationSection = value;
    }

    /**
     * Gets the value of the specificationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationUrl() {
        if (specificationUrl == null) {
            return "";
        } else {
            return specificationUrl;
        }
    }

    /**
     * Sets the value of the specificationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationUrl(String value) {
        this.specificationUrl = value;
    }

    /**
     * Gets the value of the appinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppinfo() {
        if (appinfo == null) {
            return "";
        } else {
            return appinfo;
        }
    }

    /**
     * Sets the value of the appinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppinfo(String value) {
        this.appinfo = value;
    }

}
