//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 10:04:16 AM CST 
//


package org.web3d.x3d.util.x3duom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}SimpleTypeEnumerations" minOccurs="0"/&gt;
 *         &lt;element ref="{}FieldTypes" minOccurs="0"/&gt;
 *         &lt;element ref="{}AbstractObjectTypes" minOccurs="0"/&gt;
 *         &lt;element ref="{}AbstractNodeTypes" minOccurs="0"/&gt;
 *         &lt;element ref="{}ConcreteNodes" minOccurs="0"/&gt;
 *         &lt;element ref="{}Statements" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" type="{}versionValues" default="3.3" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "simpleTypeEnumerations",
    "fieldTypes",
    "abstractObjectTypes",
    "abstractNodeTypes",
    "concreteNodes",
    "statements"
})
@XmlRootElement(name = "X3dUnifiedObjectModel")
public class X3DUnifiedObjectModel {

    @XmlElement(name = "SimpleTypeEnumerations")
    protected SimpleTypeEnumerations simpleTypeEnumerations;
    @XmlElement(name = "FieldTypes")
    protected FieldTypes fieldTypes;
    @XmlElement(name = "AbstractObjectTypes")
    protected AbstractObjectTypes abstractObjectTypes;
    @XmlElement(name = "AbstractNodeTypes")
    protected AbstractNodeTypes abstractNodeTypes;
    @XmlElement(name = "ConcreteNodes")
    protected ConcreteNodes concreteNodes;
    @XmlElement(name = "Statements")
    protected Statements statements;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the simpleTypeEnumerations property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleTypeEnumerations }
     *     
     */
    public SimpleTypeEnumerations getSimpleTypeEnumerations() {
        return simpleTypeEnumerations;
    }

    /**
     * Sets the value of the simpleTypeEnumerations property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleTypeEnumerations }
     *     
     */
    public void setSimpleTypeEnumerations(SimpleTypeEnumerations value) {
        this.simpleTypeEnumerations = value;
    }

    /**
     * Gets the value of the fieldTypes property.
     * 
     * @return
     *     possible object is
     *     {@link FieldTypes }
     *     
     */
    public FieldTypes getFieldTypes() {
        return fieldTypes;
    }

    /**
     * Sets the value of the fieldTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldTypes }
     *     
     */
    public void setFieldTypes(FieldTypes value) {
        this.fieldTypes = value;
    }

    /**
     * Gets the value of the abstractObjectTypes property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractObjectTypes }
     *     
     */
    public AbstractObjectTypes getAbstractObjectTypes() {
        return abstractObjectTypes;
    }

    /**
     * Sets the value of the abstractObjectTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractObjectTypes }
     *     
     */
    public void setAbstractObjectTypes(AbstractObjectTypes value) {
        this.abstractObjectTypes = value;
    }

    /**
     * Gets the value of the abstractNodeTypes property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractNodeTypes }
     *     
     */
    public AbstractNodeTypes getAbstractNodeTypes() {
        return abstractNodeTypes;
    }

    /**
     * Sets the value of the abstractNodeTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractNodeTypes }
     *     
     */
    public void setAbstractNodeTypes(AbstractNodeTypes value) {
        this.abstractNodeTypes = value;
    }

    /**
     * Gets the value of the concreteNodes property.
     * 
     * @return
     *     possible object is
     *     {@link ConcreteNodes }
     *     
     */
    public ConcreteNodes getConcreteNodes() {
        return concreteNodes;
    }

    /**
     * Sets the value of the concreteNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcreteNodes }
     *     
     */
    public void setConcreteNodes(ConcreteNodes value) {
        this.concreteNodes = value;
    }

    /**
     * Gets the value of the statements property.
     * 
     * @return
     *     possible object is
     *     {@link Statements }
     *     
     */
    public Statements getStatements() {
        return statements;
    }

    /**
     * Sets the value of the statements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statements }
     *     
     */
    public void setStatements(Statements value) {
        this.statements = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "3.3";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
